// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6AceufgiRoz7g1yQmgVuTblxnA6CSlcM',
    appId: '1:369093509541:web:cba9e78ec9d26fad12284c',
    messagingSenderId: '369093509541',
    projectId: 'myapplication-d4e4740a-e28a9',
    authDomain: 'myapplication-d4e4740a-e28a9.firebaseapp.com',
    storageBucket: 'myapplication-d4e4740a-e28a9.firebasestorage.app',
    measurementId: 'G-ZGNQX41REN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD91o51l08MAaXtx4yaC_TbPro7XY_T6Lk',
    appId: '1:369093509541:android:58678584ae6e6ff112284c',
    messagingSenderId: '369093509541',
    projectId: 'myapplication-d4e4740a-e28a9',
    storageBucket: 'myapplication-d4e4740a-e28a9.firebasestorage.app',
    iosClientId: '369093509541-om9smtqk3cn7g3jphtcfifk88pl0tile.apps.googleusercontent.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnLRMcdS8WQ-e3FPJshbQxVz8mWm9eU_w',
    appId: '1:1077301608049:ios:7bc197882b01c76914e5d0',
    messagingSenderId: '1077301608049',
    projectId: 'myapplication-d4e4740a',
    storageBucket: 'myapplication-d4e4740a.firebasestorage.app',
    iosBundleId: 'com.example.cloudauthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnLRMcdS8WQ-e3FPJshbQxVz8mWm9eU_w',
    appId: '1:1077301608049:ios:7bc197882b01c76914e5d0',
    messagingSenderId: '1077301608049',
    projectId: 'myapplication-d4e4740a',
    storageBucket: 'myapplication-d4e4740a.firebasestorage.app',
    iosBundleId: 'com.example.cloudauthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4vQvE9sy4lUSvGHM76HtTi_9CuSUOH9c',
    appId: '1:1077301608049:web:5ad798dfc434143814e5d0',
    messagingSenderId: '1077301608049',
    projectId: 'myapplication-d4e4740a',
    authDomain: 'myapplication-d4e4740a.firebaseapp.com',
    storageBucket: 'myapplication-d4e4740a.firebasestorage.app',
  );

}